docker_image: "nsls2/linux-anvil-cos7-x86_64:latest"
env_version: &version "2022-2.3"
python_version: &pythonver "3.8"
python_version_string: &pythonverstr "py38"
env_name: !concat [*version, "-", *pythonverstr]
conda_env_file: !concat ["env-", *pythonverstr, ".yml"]
conda_binary: "mamba"
pkg_name: ""
pkg_version: ""
# extra_packages: "nsls2-collection=2021C2.0=*_0 tmate mamba"
extra_packages: "tmate mamba"
channels: "-c conda-forge"
#extra_cmd_before_install: "yum install mesa-libGL mesa-libGL-devel -y"
extra_cmd_before_install: "yum install mesa-libGL -y"
extra_cmd_after_install: "conda remove perl --force -y"
docker_upload:
  - ghcr
  - dockerhub
  # - quay
zenodo_upload: true
zenodo_metadata:
  metadata:
    title: "NSLS-II collection conda environment"
    upload_type: "software"
    description: "NSLS-II collection environment deployed to the experimental floor."
    version: *version
    creators:
      - name: "Rakitin, Maksim"
        affiliation: "NSLS-II, Brookhaven National Laboratory"
        orcid: "0000-0003-3685-852X"
      - name: "Bischof, Garrett"
        affiliation: "NSLS-II, Brookhaven National Laboratory"
